image:
- Visual Studio 2017
- Ubuntu

build_script:
- echo "my emscripten build"

for:
-
  matrix:
    only:
      - image: Ubuntu

  install:
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - ./emsdk install latest
  - ./emsdk activate latest
  - source ./emsdk_env.sh
  - cd $appveyor_build_folder
  
-
  matrix:
    only:
      - image: Visual Studio 2017

  install:
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - emsdk install latest
  - emsdk activate latest
  - emsdk_env.bat
  - cd %appveyor_build_folder%
